import React, { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Award, CheckCircle2, ChevronRight, Dumbbell, FileVideo, ShieldCheck, Trophy, Upload, Users, Video, Camera, CircleX, Filter, Minus, Plus, Check } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { addDoc, collection, getDocs, limit, orderBy, query, where } from 'firebase/firestore';
import { db, storage } from '../firebase';
import { getDownloadURL, ref, uploadBytes } from 'firebase/storage';
import { useUser } from '../UserContext';
import { validationService } from '../services/validationService';
import './PowerLift.css';
import './PowerLiftFlow.css';
import './PowerLiftFidelity.css';
import './PowerLiftUpload.css';
import './PowerLiftMobile.css';

type Exercise = 'supino' | 'agachamento' | 'terra';
type RecordRow = { id: string; userId: string; userName?: string; userPhoto?: string; gymName?: string; exercise: Exercise; weight: number; videoStatus?: string };
const exercises: Array<{ id: Exercise; title: string; accent: string; image: string; icon: React.ReactNode }> = [
  { id: 'supino', title: 'SUPINO RETO', accent: 'gold', image: '/powerlift-supino.jpg', icon: <Dumbbell /> },
  { id: 'agachamento', title: 'AGACHAMENTO LIVRE', accent: 'green', image: '/powerlift-agachamento.jpg', icon: <Award /> },
  { id: 'terra', title: 'LEVANTAMENTO TERRA', accent: 'violet', image: '/powerlift-terra.jpg', icon: <Dumbbell /> },
];
const framesFromVideo = (file: File) => new Promise<string[]>((resolve) => { const url=URL.createObjectURL(file); const video=document.createElement('video'); const out:string[]=[]; let done=false; const finish=()=>{if(done)return;done=true;URL.revokeObjectURL(url);resolve(out)}; video.muted=true; video.playsInline=true; video.src=url; video.onloadedmetadata=()=>{const take=(time:number)=>{video.currentTime=time};let step=0;video.onseeked=()=>{const c=document.createElement('canvas');const ratio=Math.min(1,512/(video.videoWidth||512));c.width=(video.videoWidth||512)*ratio;c.height=(video.videoHeight||512)*ratio;c.getContext('2d')?.drawImage(video,0,0,c.width,c.height);out.push(c.toDataURL('image/jpeg',.65));step++;step<3?take(Math.min((video.duration||2)*step/3,Math.max(.1,(video.duration||2)-.1))):finish()};take(.1)};video.onerror=finish;setTimeout(finish,6000)});

export function PowerLift() {
  const navigate = useNavigate(); const { user } = useUser(); const [records, setRecords] = useState<RecordRow[]>([]); const [loading, setLoading] = useState(true); const [modal, setModal] = useState<'rules' | 'videos' | 'register' | null>(null); const [selected, setSelected] = useState<Exercise>('supino'); const [view, setView] = useState<'home'|'ranking'|'register'|'record'|'processing'|'manual-review'|'approved'|'rejected'|'rules'>('home'); const [weight, setWeight] = useState(0); const [videoFile,setVideoFile]=useState<File|null>(null); const [reasons,setReasons]=useState<string[]>([]);
  useEffect(() => { let mounted = true; (async () => { try { const snap = await getDocs(query(collection(db, 'power_records'), where('videoStatus', '==', 'approved'), orderBy('weight', 'desc'), limit(100))); if (mounted) setRecords(snap.docs.map(item => ({ id:item.id, ...(item.data() as Omit<RecordRow, 'id'>) }))); } catch { if (mounted) setRecords([]); } finally { if (mounted) setLoading(false); } })(); return () => { mounted = false; }; }, []);
  const byExercise = (id: Exercise) => records.filter(row => row.exercise === id).sort((a,b) => b.weight-a.weight);
  const personalBest = (id: Exercise) => byExercise(id).find(row => row.userId === user?.uid)?.weight ?? null;
  const top = useMemo(() => [...records].sort((a,b)=>b.weight-a.weight).slice(0,3), [records]);
  const stat = (label: string, icon: React.ReactNode, value: React.ReactNode) => <article className="power-stat"><span>{icon}</span><small>{label}</small><b>{value}</b></article>;
  const submitVideo=async()=>{if(!user||!videoFile)return;setView('processing');try{const frames=await framesFromVideo(videoFile);const result=await validationService.validatePowerVideo(frames,selected,weight);const motives=result.motivos||[result.analysis];const confidence=Number(result.confidence||0);const audit=async(resultName:'VALIDADO'|'AUDITORIA_MANUAL'|'REPROVADO',videoUrl='')=>addDoc(collection(db,'power_audit_logs'),{userId:user.uid,userName:user.displayName||user.name||'Atleta',exercise:selected,declaredWeight:weight,estimatedWeight:result.estimatedWeight||weight,confidence,result:resultName,motivos:motives,videoUrl,timestamp:new Date().toISOString(),aiVersion:'Invictus Audit'}).catch(error=>console.warn('[PowerLift] audit log unavailable',error));setReasons(motives);if(!result.isValid&&!result.isManualReview){await audit('REPROVADO');setView('rejected');return}const path=ref(storage,`power_records/${user.uid}/${Date.now()}_${videoFile.name}`);const uploaded=await uploadBytes(path,videoFile);const videoUrl=await getDownloadURL(uploaded.ref);const videoStatus=result.isValid?'approved':'manual_review';await addDoc(collection(db,'power_records'),{userId:user.uid,userName:user.displayName||user.name||'Atleta',userPhoto:user.photoURL||'',gymId:user.gymId||'',gymName:user.gymName||'',city:user.city||'',exercise:selected,weight,videoUrl,videoStatus,userMessage:result.analysis,reports:[],date:new Date().toISOString().slice(0,10)});await audit(result.isValid?'VALIDADO':'AUDITORIA_MANUAL',videoUrl);if(result.isValid){setRecords(old=>[{id:`local-${Date.now()}`,userId:user.uid,userName:user.displayName||user.name,userPhoto:user.photoURL,gymName:user.gymName,exercise:selected,weight,videoStatus:'approved'},...old]);setView('approved')}else setView('manual-review')}catch{setReasons(['Não foi possível concluir o envio. Tente novamente com conexão estável.']);setView('rejected')}};
  if (view !== 'home') return <PowerLiftFlow view={view} exercise={selected} records={records} userId={user?.uid} weight={weight} setWeight={setWeight} videoFile={videoFile} reasons={reasons} onFile={setVideoFile} onSubmit={submitVideo} onBack={()=>setView('home')} onView={setView} onExercise={setSelected} />;
  return <main className="power-screen"><header className="power-header"><button onClick={()=>navigate('/challenges')}><ArrowLeft /></button><div><h1>DESAFIO DE FORÇA <em>PRO</em></h1><p>Supere seus limites. Prove sua força.</p></div><button className="power-rules" onClick={()=>setModal('rules')}><FileVideo /> REGRAS</button></header>
    <section className="power-panel power-ranking"><div className="power-panel-title"><h2>RANKING GERAL</h2><span><Users /> {records.length || '—'} atletas</span></div><div className="power-podium">{[1,0,2].map((rank, position) => { const row=top[rank]; return <button key={rank} onClick={()=>navigate('/rankings')} className={`power-podium-item pos-${position}`}>{row?.userPhoto ? <img src={row.userPhoto} alt="" /> : <span className="power-avatar">{row?.userName?.slice(0,1) || '—'}</span>}<i>{rank+1}</i><b>{row?.userName || 'Sem registros'}</b><strong>{row ? `${row.weight} kg` : '—'}</strong></button>})}<ChevronRight className="power-next" /></div></section>
    <section className="power-panel power-how"><h2>COMO FUNCIONA</h2><div>{[[<Video/>, 'Grave seu vídeo', 'Execute o movimento com carga visível'], [<Upload/>, 'Envie para validação', 'Nossa IA analisará seu vídeo'], [<ShieldCheck/>, 'Validamos seu desafio', 'Garantimos justiça e integridade'], [<Trophy/>, 'Receba sua posição', 'Entre no ranking e acompanhe sua evolução']].map(([icon,title,text],i)=><article key={i}><span>{icon}</span><b>{title}</b><small>{text}</small></article>)}</div></section>
    <section className="power-panel power-modalities"><h2>MODALIDADES</h2><div className="power-cards">{exercises.map(item => { const best=personalBest(item.id); const standing=byExercise(item.id).findIndex(row=>row.userId===user?.uid); return <article key={item.id} className={`power-card ${item.accent}`}><div className="power-card-top"><span>{item.icon}</span><div><b>{item.title}</b><small><i /> Ranking ativo</small></div></div><img src={item.image} alt=""/><div className="power-card-data"><small>SUA MELHOR MARCA</small><strong>{best ? `${best} kg` : '—'}</strong><hr/><small>SUA POSIÇÃO</small><strong>{standing >= 0 ? `${standing+1}º` : '—'}</strong><button onClick={()=>{setSelected(item.id);setView('ranking')}}>VER RANKING</button></div></article> })}</div></section>
    <section className="power-panel power-stats"><h2>SUAS ESTATÍSTICAS GERAIS</h2><div>{stat('DESAFIOS ENVIADOS',<Trophy/>,records.filter(row=>row.userId===user?.uid).length)}{stat('DESAFIOS APROVADOS',<ShieldCheck/>,records.filter(row=>row.userId===user?.uid && row.videoStatus==='approved').length)}{stat('TAXA DE APROVAÇÃO',<Award/>, '—')}{stat('PONTUAÇÃO TOTAL',<Trophy/>, '—')}</div></section>
    <section className="power-actions"><button className="power-register" onClick={()=>setView('register')}><Dumbbell /><span>REGISTRAR NOVO LEVANTAMENTO<small>Envie seu vídeo e desafie seus limites</small></span></button><button onClick={()=>setModal('videos')}><FileVideo /><span>MEUS VÍDEOS<small>Ver envios e status</small></span></button></section>
    {modal && <div className="power-overlay" onClick={()=>setModal(null)}><section onClick={e=>e.stopPropagation()}><button className="power-close" onClick={()=>setModal(null)}>×</button>{modal==='rules' && <><h2>REGRAS DO DESAFIO</h2><p>Grave o movimento completo, com carga visível e ambiente de academia identificável. Cada registro passa por validação antes de entrar no ranking.</p></>}{modal==='videos' && <><h2>MEUS VÍDEOS</h2>{records.filter(row=>row.userId===user?.uid).map(row=><p key={row.id}>{row.exercise.toUpperCase()} · {row.weight} kg · {row.videoStatus === 'approved' ? 'Aprovado' : 'Em análise'}</p>)}{!records.some(row=>row.userId===user?.uid)&&<p>Nenhum vídeo enviado ainda.</p>}</>}{modal==='register' && <><h2>REGISTRAR LEVANTAMENTO</h2><select value={selected} onChange={e=>setSelected(e.target.value as Exercise)}>{exercises.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select><p>O envio de vídeo será conectado ao fluxo de validação na próxima etapa do Power Lift.</p></>}</section></div>}
  </main>;
}

function PowerLiftFlow({ view, exercise, records, userId, weight, setWeight, videoFile, reasons, onFile, onSubmit, onBack, onView, onExercise }: { view:string; exercise:Exercise; records:RecordRow[]; userId?:string; weight:number; setWeight:(n:number)=>void; videoFile:File|null; reasons:string[]; onFile:(f:File|null)=>void; onSubmit:()=>void; onBack:()=>void; onView:(v:any)=>void; onExercise:(x:Exercise)=>void }) {
  const item = exercises.find(x=>x.id===exercise)!; const rows = records.filter(r=>r.exercise===exercise).sort((a,b)=>b.weight-a.weight); const mine=rows.findIndex(r=>r.userId===userId); const [rankingTab,setRankingTab]=useState<'general'|'mine'>('general'); const visibleRows=rankingTab==='mine'?rows.filter(row=>row.userId===userId):rows; const heading = view==='ranking' ? item.title : view==='register' ? 'REGISTRAR LEVANTAMENTO' : view==='record' ? item.title : view==='processing' ? 'PROCESSANDO VÍDEO' : view==='manual-review' ? 'EM REVISÃO MANUAL' : view==='approved' ? 'LEVANTAMENTO APROVADO!' : view==='rejected' ? 'LEVANTAMENTO RECUSADO' : 'REGRAS DO DESAFIO';
  return <main className={`power-flow ${item.accent}`}><header><button onClick={onBack}><ArrowLeft /></button><div><h1>{heading}</h1><p>{view==='ranking'?'Ranking ativo':view==='record'?`Carga informada: ${weight || '—'} kg`:view==='rules'?'Entenda como funciona e garanta que seu vídeo seja aprovado.':''}</p></div>{view==='ranking'&&<button className="power-filter"><Filter/></button>}</header>
  {view==='ranking'&&<><div className="power-flow-tabs"><button className={rankingTab==='general'?'active':''} onClick={()=>setRankingTab('general')}>GERAL</button><button className={rankingTab==='mine'?'active':''} onClick={()=>setRankingTab('mine')}>MINHAS MARCAS</button></div><img className="power-flow-hero" src={item.image} alt=""/><div className="power-flow-columns"><span>POSIÇÃO</span><span>ATLETA</span><span>MELHOR MARCA</span></div><section className="power-flow-rank">{visibleRows.length?visibleRows.map((r,i)=><article key={r.id} className={r.userId===userId?'mine':''}><b>{rankingTab==='general'?i+1:'•'}</b>{r.userPhoto?<img src={r.userPhoto} alt=""/>:<span/>}<div><strong>{r.userName||'Atleta'}</strong><small>{r.gymName||'Academia não informada'}</small></div><em>{r.weight} kg</em></article>):<p>{rankingTab==='mine'?'Você ainda não possui um levantamento aprovado nesta modalidade.':'Nenhum levantamento aprovado nesta modalidade ainda.'}</p>}</section><button className="power-flow-primary" onClick={()=>{setRankingTab('mine');window.setTimeout(()=>document.querySelector('.power-flow-rank .mine')?.scrollIntoView({behavior:'smooth',block:'center'}),0)}}>{mine>=0?`◎  VER MINHA POSIÇÃO`:'◎  SEM POSIÇÃO AINDA'}</button></>}
  {view==='register'&&<><p className="power-flow-label">ESCOLHA A MODALIDADE</p><div className="power-flow-choices">{exercises.map(x=><button className={x.id===exercise?'active':''} onClick={()=>onExercise(x.id)} key={x.id}>{x.icon}<span>{x.title}</span></button>)}</div><p className="power-flow-label">INFORME SUA MELHOR MARCA</p><section className="power-flow-weight"><button onClick={()=>setWeight(Math.max(0,weight-2.5))}><Minus/></button><b>{weight||'—'} <small>kg</small></b><button onClick={()=>setWeight(weight+2.5)}><Plus/></button></section><section className="power-flow-rules"><b>REGRAS IMPORTANTES</b><p>• Vídeo obrigatório<br/>• Mostre os pesos utilizados<br/>• Execução completa e válida<br/>• Ambiente de academia</p></section><button className="power-flow-primary" disabled={!weight} onClick={()=>onView('record')}>CONTINUAR</button></>}
  {view==='record'&&<><div className="power-flow-camera" style={{backgroundImage:`url(${item.image})`}}><span><i/> REC</span><b>00:00:00</b></div><section className="power-flow-rules"><b>ORIENTAÇÕES PARA GRAVAÇÃO</b><p>Mostre os pesos utilizados <Check/><br/>Execute o movimento completo <Check/><br/>Ambiente de academia visível <Check/><br/>Câmera fixa e sem edições <Check/></p></section><input id="power-video" className="power-video-input" type="file" accept="video/*" capture="environment" onChange={e=>onFile(e.target.files?.[0]||null)}/><label className="power-record-button" htmlFor="power-video"><Camera/></label><strong className="power-record-copy">{videoFile?'VÍDEO SELECIONADO':'TOQUE PARA GRAVAR'}<small>{videoFile?.name||'Grave todo o movimento em um único take'}</small></strong>{videoFile&&<button className="power-flow-primary" onClick={onSubmit}>ENVIAR PARA VALIDAÇÃO</button>}</>}
  {view==='processing'&&<section className="power-result"><div className="power-progress">65%</div><p>Analisando seu vídeo…</p><article>Nossa IA está verificando:<br/><Check/> Ambiente de academia<br/><Check/> Presença de pesos<br/><Check/> Execução do movimento<br/><Check/> Amplitude e técnica<br/><Check/> Integridade do vídeo</article><small>A decisão real é exibida somente após a validação do vídeo.</small></section>}
  {view==='manual-review'&&<section className="power-result"><ShieldCheck/><h2>VÍDEO EM REVISÃO</h2><p>Seu envio foi registrado para auditoria manual. Ele não entra no ranking nem gera pontuação até uma aprovação real.</p><article>{item.title}<b>{weight} kg</b><small>Status: aguardando revisão</small></article><button className="power-flow-primary" onClick={onBack}>VOLTAR AO DESAFIO</button></section>}
  {view==='approved'&&<section className="power-result is-ok"><CheckCircle2/><h2>LEVANTAMENTO APROVADO!</h2><p>Apenas exibido após aprovação real.</p><article>{item.title}<b>{weight} kg</b></article><button className="power-flow-primary" onClick={()=>onView('ranking')}>IR PARA O RANKING</button></section>}
  {view==='rejected'&&<section className="power-result is-no"><CircleX/><h2>LEVANTAMENTO RECUSADO</h2><p>Seu vídeo não atendeu às regras.</p><article>{reasons.map(reason=><p key={reason}>⊗ {reason}</p>)}</article><button className="power-flow-primary" onClick={()=>onView('record')}>ENVIAR NOVO VÍDEO</button></section>}
  {view==='rules'&&<section className="power-flow-rules power-full-rules"><h2>COMO FUNCIONA</h2><p>Grave seu melhor levantamento em vídeo e conquiste sua posição no ranking. Quanto maior o peso validado, maior a posição.</p><h2>REGRAS DO VÍDEO</h2><p>Ambiente de academia, peso visível, execução completa e câmera fixa. Vídeos com cortes, edições ou informações insuficientes podem ser recusados.</p></section>}
  </main>;
}
