import React, { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Bell, Building2, Check, ChevronRight, CircleDollarSign, Globe2, Landmark, Languages, LockKeyhole, MapPin, Moon, Plus, Search, Settings, ShieldCheck, Target, Trash2, Watch, WalletCards } from 'lucide-react';
import { useLocation, useNavigate } from 'react-router-dom';
import { useUser } from '../UserContext';
import { gymService } from '../services/gymService';
import { getCurrentLocation } from '../lib/locationUtils';
import { auth } from '../firebase';

type Page = 'academy' | 'academy-search' | 'academy-confirm' | 'wearables' | 'wallet' | 'goals' | 'security' | 'preferences';
const title: Record<Page, string> = { academy: 'MINHA ACADEMIA', 'academy-search': 'ALTERAR ACADEMIA', 'academy-confirm': 'ACADEMIA SELECIONADA', wearables: 'DISPOSITIVOS E RELÓGIOS', wallet: 'CARTEIRA', goals: 'METAS', security: 'SEGURANÇA E PRIVACIDADE', preferences: 'CONFIGURAÇÕES' };
const pathToPage = (path: string): Page => path.includes('academy/search') ? 'academy-search' : path.includes('academy/confirm') ? 'academy-confirm' : path.includes('academy') ? 'academy' : path.includes('wearables') ? 'wearables' : path.includes('wallet') ? 'wallet' : path.includes('goals') ? 'goals' : path.includes('security') ? 'security' : 'preferences';

export function ProfileSecondary() {
  const navigate = useNavigate(); const location = useLocation(); const { user, refreshUser } = useUser();
  const page = pathToPage(location.pathname); const [query, setQuery] = useState(''); const [gyms, setGyms] = useState<any[]>([]); const [selected, setSelected] = useState<any>(location.state?.gym || null); const [loading, setLoading] = useState(false); const [notice, setNotice] = useState('');
  const [wallet, setWallet] = useState<any>(null); const [transactions, setTransactions] = useState<any[]>([]);
  const go = (next: Page, state?: any) => navigate(`/profile/${next.replace('academy-', 'academy/')}`, { state });
  useEffect(() => { if (page !== 'academy-search') return; let alive = true; (async () => { setLoading(true); try { const p = await getCurrentLocation(true); const results = await gymService.searchNearbyGyms(p.lat, p.lng); if (alive) setGyms(results); } catch (e: any) { if (alive) setNotice(e.message || 'Não foi possível localizar academias próximas.'); } finally { if (alive) setLoading(false); } })(); return () => { alive = false; }; }, [page]);
  useEffect(() => { if (page !== 'wallet') return; (async () => { try { const token = await auth.currentUser?.getIdToken(); const headers = token ? { Authorization: `Bearer ${token}` } : {}; const [summary, tx] = await Promise.all([fetch('/api/financial?action=summary', { headers }), fetch('/api/financial?action=transactions', { headers })]); const s = await summary.json(); const t = await tx.json(); setWallet(s.success ? s.wallet : null); setTransactions(t.success ? t.transactions || [] : []); } catch { setNotice('Não foi possível carregar sua carteira agora.'); } })(); }, [page]);
  const search = async (event: React.FormEvent) => { event.preventDefault(); if (!query.trim()) return; setLoading(true); setNotice(''); try { const p = await getCurrentLocation(true); setGyms(await gymService.searchGymsByText(query, p.lat, p.lng)); } catch (e: any) { setNotice(e.message || 'Busca indisponível.'); } finally { setLoading(false); } };
  const confirmGym = async () => { if (!selected) return; setLoading(true); try { const point = selected.geometry?.location || {}; await gymService.joinGym({ place_id: selected.place_id || selected.id, name: selected.name, latitude: typeof point.lat === 'function' ? point.lat() : point.lat ?? selected.lat, longitude: typeof point.lng === 'function' ? point.lng() : point.lng ?? selected.lng, photo_url: selected.photoUrl, address: selected.vicinity || selected.address }); await refreshUser?.(); navigate('/profile'); } catch (e: any) { setNotice(e.message || 'Não foi possível atualizar sua academia.'); } finally { setLoading(false); } };
  const rows = (items: Array<{ icon: React.ReactNode; label: string; detail?: string; action?: () => void; danger?: boolean }>) => <section className="profile-flow-list">{items.map((item, i) => <button key={item.label} onClick={item.action} className={item.danger ? 'is-danger' : ''}><span className="profile-flow-row-icon">{item.icon}</span><span><b>{item.label}</b>{item.detail && <small>{item.detail}</small>}</span><ChevronRight /></button>)}</section>;
  const currentGym = user?.gymName || 'Nenhuma academia vinculada';
  const content = useMemo(() => {
    if (page === 'academy') return <><p className="profile-flow-section-label">ACADEMIA ATUAL</p><section className="profile-flow-card profile-flow-gym-current"><Building2 /><div><b>{currentGym}</b><small>{user?.gymAddress || user?.city || 'Informações disponíveis no seu perfil'}</small><em>ATIVA</em></div></section><p className="profile-flow-section-label">INFORMAÇÕES</p>{rows([{ icon:<MapPin />, label:'Endereço', detail:user?.gymAddress || 'Não informado' }, { icon:<Target />, label:'Distância até você', detail:'Disponível com sua localização' }, { icon:<ShieldCheck />, label:'Vínculo', detail:'Academia associada ao seu perfil' }])}<button className="profile-flow-primary" onClick={() => go('academy-search')}>ALTERAR ACADEMIA</button></>;
    if (page === 'academy-search') return <><form className="profile-flow-search" onSubmit={search}><Search /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Buscar academia por nome" /><button aria-label="Buscar"><Search /></button></form><p className="profile-flow-section-label">{query ? 'RESULTADOS' : 'ACADEMIAS PRÓXIMAS'}</p>{loading && <p className="profile-flow-muted">Buscando com sua localização atual…</p>}{rows(gyms.map(g => ({ icon:<Building2 />, label:g.name, detail:`${g.vicinity || g.address || 'Endereço não informado'}${g.distance ? ` · ${g.distance}` : ''}`, action:() => { setSelected(g); go('academy-confirm', { gym:g }); } })))}{!loading && !gyms.length && <p className="profile-flow-muted">Nenhuma academia encontrada nesta área.</p>}</>;
    if (page === 'academy-confirm') return <section className="profile-flow-confirm"><span><Building2 /></span><Check className="profile-flow-confirm-check" /><p>Academia selecionada!</p><h2>{selected?.name || 'Academia'}</h2><small>{selected?.vicinity || selected?.address || 'Localização informada pela busca'}</small><em>{selected?.distance || 'Distância calculada pela localização'}</em><button className="profile-flow-primary" disabled={loading} onClick={confirmGym}>DEFINIR COMO MINHA ACADEMIA</button><button className="profile-flow-text" onClick={() => navigate(-1)}>CANCELAR</button></section>;
    if (page === 'wearables') return <><p className="profile-flow-section-label">DISPOSITIVOS CONECTADOS</p>{rows([{icon:<Watch/>,label:'Gerenciar conexões',detail:'Apple Health, Health Connect e Strava',action:()=>navigate('/wearables')}])}<button className="profile-flow-primary" onClick={() => navigate('/wearables')}><Plus /> CONECTAR NOVO DISPOSITIVO</button><p className="profile-flow-section-label">SINCRONIZAÇÃO</p>{rows([{icon:<ShieldCheck/>,label:'Dados e permissões',detail:'Consulte o status real de cada integração',action:()=>navigate('/wearables')}])}</>;
    if (page === 'wallet') return <><section className="profile-flow-card profile-flow-balance"><small>SALDO DISPONÍVEL</small><b>R$ {(wallet?.redeemableBalance || 0).toLocaleString('pt-BR',{minimumFractionDigits:2})}</b><span>Histórico, saques e extratos</span></section>{rows([{icon:<WalletCards/>,label:'Extrato',detail:`${transactions.length} registros`,action:()=>navigate('/wallet')},{icon:<CircleDollarSign/>,label:'Saques',detail:'Gerencie solicitações disponíveis',action:()=>navigate('/wallet')},{icon:<Landmark/>,label:'Histórico',detail:'Transações reais da sua conta',action:()=>navigate('/wallet')}])}<button className="profile-flow-primary" onClick={()=>navigate('/wallet')}>VER EXTRATO COMPLETO</button></>;
    if (page === 'goals') return <><p className="profile-flow-muted">Suas metas de treino serão exibidas conforme forem registradas no seu plano.</p>{rows([{icon:<Target/>,label:'Objetivo principal',detail:user?.objective || 'Não definido',action:()=>navigate('/settings?tab=profile')},{icon:<Target/>,label:'Frequência semanal',detail:user?.weeklyFrequency || 'Não definida',action:()=>navigate('/settings?tab=profile')}])}<button className="profile-flow-primary" onClick={()=>navigate('/settings?tab=profile')}><Plus /> ADICIONAR NOVA META</button></>;
    if (page === 'security') return <><p className="profile-flow-section-label">SEGURANÇA</p>{rows([{icon:<LockKeyhole/>,label:'Alterar senha',detail:'Gerencie a credencial da sua conta',action:()=>navigate('/settings?tab=profile')},{icon:<ShieldCheck/>,label:'Autenticação em duas etapas',detail:'Disponibilidade conforme seu provedor de login'},{icon:<Watch/>,label:'Sessões ativas',detail:'Dispositivos autenticados'}])}<p className="profile-flow-section-label">PRIVACIDADE</p>{rows([{icon:<Globe2/>,label:'Quem pode ver meu perfil',detail:'Preferências de visibilidade'},{icon:<ShieldCheck/>,label:'Permissões e dados',detail:'Gerencie consentimentos',action:()=>navigate('/settings')}])}{rows([{icon:<Trash2/>,label:'Excluir minha conta',detail:'Ação irreversível',danger:true,action:()=>navigate('/settings')}])}</>;
    return <><p className="profile-flow-section-label">GERAL</p>{rows([{icon:<Bell/>,label:'Notificações',action:()=>navigate('/settings')},{icon:<Settings/>,label:'Unidades',detail:'Métricas configuradas pelo aplicativo',action:()=>navigate('/settings')},{icon:<Moon/>,label:'Tema',detail:'Preferência atual do dispositivo',action:()=>navigate('/settings')},{icon:<Languages/>,label:'Idioma',detail:'Português',action:()=>navigate('/settings')}])}<p className="profile-flow-section-label">SOBRE</p>{rows([{icon:<ShieldCheck/>,label:'Sobre o Invictus',action:()=>navigate('/settings')},{icon:<Landmark/>,label:'Termos de uso',action:()=>navigate('/settings')},{icon:<LockKeyhole/>,label:'Política de privacidade',action:()=>navigate('/settings')}])}<button className="profile-flow-danger" onClick={()=>auth.signOut().then(()=>{window.location.href='/';})}>SAIR DA CONTA</button></>;
  }, [page, user, currentGym, gyms, loading, notice, query, selected, wallet, transactions]);
  return <main className="profile-flow-screen"><header><button onClick={()=>navigate(page === 'academy-search' ? '/profile/academy' : '/profile')} aria-label="Voltar"><ArrowLeft /></button><h1>{title[page]}</h1></header>{notice && <p className="profile-flow-notice">{notice}</p>}<div className="profile-flow-content">{content}</div></main>;
}
