import { ArrowLeft, Bike, Check, ChevronDown, ChevronRight, Clock3, Dumbbell, Footprints, Gauge, MapPin, Navigation, PersonStanding, Play, Plus, Timer, Waves, Zap } from 'lucide-react';
import type { ActivitySession } from '../types';
import { ActivityMapView } from './ActivityMapView';

export type ChallengeFlowScreen = 'workout-details' | 'workout-checkin' | 'cardio-picker' | 'cardio-checkin' | 'active' | 'workout-complete' | 'cardio-complete' | 'cardio-summary' | 'day-progress';

export type CardioOption = { id: string; label: string; icon: 'run' | 'walk' | 'bike' | 'treadmill' | 'elliptical' | 'stairs' | 'row' | 'swim' | 'hiit'; gps: boolean };
export const CARDIO_OPTIONS: CardioOption[] = [
  { id: 'running', label: 'Corrida ao ar livre', icon: 'run', gps: true }, { id: 'walking', label: 'Caminhada ao ar livre', icon: 'walk', gps: true },
  { id: 'bike', label: 'Bike ao ar livre', icon: 'bike', gps: true }, { id: 'treadmill', label: 'Esteira', icon: 'treadmill', gps: false },
  { id: 'stationary_bike', label: 'Bike ergométrica', icon: 'bike', gps: false }, { id: 'elliptical', label: 'Elíptico / Transport', icon: 'elliptical', gps: false },
  { id: 'rowing', label: 'Remo indoor', icon: 'row', gps: false }, { id: 'stair_climber', label: 'Escada / Stairmaster', icon: 'stairs', gps: false },
  { id: 'swimming', label: 'Natação', icon: 'swim', gps: false }, { id: 'hiit', label: 'HIIT / Funcional', icon: 'hiit', gps: false }
];
const groups = ['Peito', 'Costas', 'Pernas', 'Ombros', 'Braços', 'Abdômen', 'Corpo todo'];
const icon = (kind: CardioOption['icon'], size = 20) => kind === 'bike' ? <Bike size={size} /> : kind === 'swim' ? <Waves size={size} /> : kind === 'treadmill' ? <Gauge size={size} /> : kind === 'row' ? <Dumbbell size={size} /> : kind === 'stairs' ? <Navigation size={size} /> : kind === 'hiit' ? <Zap size={size} /> : kind === 'walk' ? <PersonStanding size={size} /> : <Footprints size={size} />;
const time = (seconds: number) => `${String(Math.floor(seconds / 3600)).padStart(2, '0')}:${String(Math.floor(seconds % 3600 / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`;

export function ChallengeActivityFlow({ screen, group, onGroup, cardio, onCardio, session, elapsed, distance, trajectory, gymName, completedChallengeIds, onBack, onStart, onEnd, onSummary, onDone }: {
  screen: ChallengeFlowScreen; group: string; onGroup: (value: string) => void; cardio: CardioOption; onCardio: (value: CardioOption) => void;
  session: ActivitySession | null; elapsed: number; distance: number; trajectory?: Array<{ lat: number; lng: number }>; gymName: string; completedChallengeIds: string[]; onBack: () => void; onStart: (type: 'workout' | 'cardio') => void; onEnd: () => void; onSummary: () => void; onDone: () => void;
}) {
  const activeCardio = session?.type === 'cardio' || screen === 'cardio-complete' || screen === 'cardio-summary';
  const activeTitle = activeCardio ? cardio.label : `Treino de ${group}`;
  const pace = distance > .01 && elapsed ? `${Math.floor((elapsed / 60) / distance)}'${String(Math.round((elapsed / 60 / distance % 1) * 60)).padStart(2, '0')}"` : '—';
  const checkin = screen === 'workout-checkin' || screen === 'cardio-checkin';
  const complete = screen === 'workout-complete' || screen === 'cardio-complete';
  const subtitle = screen === 'workout-details' ? 'DETALHES DO DESAFIO' : screen === 'cardio-picker' ? 'SELECIONE O TIPO DE CARDIO' : checkin ? 'CHECK-IN DE PRESENÇA' : screen === 'active' ? (activeCardio ? 'CARDIO EM ANDAMENTO' : 'TREINO EM ANDAMENTO') : complete ? (screen === 'cardio-complete' ? 'CARDIO CONCLUÍDO!' : 'TREINO CONCLUÍDO!') : screen === 'cardio-summary' ? 'RESUMO DA ATIVIDADE' : 'DESAFIOS DO DIA';
  const xp = activeCardio || screen === 'cardio-complete' ? 80 : 100;
  return <main className="challenge-flow-screen"><header className="challenge-flow-header"><button aria-label="Voltar" onClick={onBack}><ArrowLeft /></button><h1>{subtitle}</h1></header>
    {screen === 'workout-details' && <section className="challenge-flow-card challenge-flow-details"><div className="challenge-flow-title"><span className="challenge-flow-icon"><Dumbbell /></span><div><small>EM ANDAMENTO</small><h2>TREINO DE MUSCULAÇÃO</h2><b>+100 XP</b></div></div><p>Realize um treino completo na academia e registre sua atividade.</p><div className="challenge-flow-panel"><strong>SELECIONE O GRUPO MUSCULAR</strong><div className="challenge-flow-groups">{groups.map(item => <button className={group === item ? 'is-selected' : ''} onClick={() => onGroup(item)} key={item}>{item}</button>)}</div></div><div className="challenge-flow-panel"><strong>PROGRESSO DO DESAFIO <em>0/1</em></strong><p>Complete 1 treino de musculação hoje</p></div><div className="challenge-flow-panel"><strong>REQUISITOS</strong><ul><li><MapPin />Check-in na academia</li><li><Clock3 />Treino de 30 a 90 minutos</li><li><Timer />Registro de frequência cardíaca</li></ul></div><button className="challenge-flow-primary" onClick={() => onStart('workout')}><Play />INICIAR TREINO</button></section>}
    {screen === 'cardio-picker' && <section className="challenge-flow-card challenge-flow-cardio-picker"><p>Escolha a modalidade que você irá realizar.</p><div className="challenge-flow-cardio-grid">{CARDIO_OPTIONS.map(item => <button className={cardio.id === item.id ? 'is-selected' : ''} key={item.id} onClick={() => onCardio(item)}>{icon(item.icon)}<span>{item.label}</span><small>{item.gps ? 'Com GPS' : 'Sem GPS'}</small></button>)}</div><p className="challenge-flow-note"><Navigation /> Corrida, caminhada e bike ao ar livre usam GPS.</p><button className="challenge-flow-primary" onClick={() => onStart('cardio')}><Play />INICIAR CARDIO</button></section>}
    {checkin && <section className="challenge-flow-checkin"><p>Confirme que você está na academia para iniciar seu treino.</p><div className="challenge-flow-radar"><MapPin /></div><span>Procurando sua localização…</span><article><small>Academia detectada</small><b>{gymName || 'Sua academia'}</b><p>Validação de presença antes do início.</p><Check /></article><button className="challenge-flow-primary" onClick={() => onStart(screen === 'workout-checkin' ? 'workout' : 'cardio')}><Check />CONFIRMAR CHECK-IN</button></section>}
    {screen === 'active' && <section className="challenge-flow-active"><button className="challenge-flow-activity-type">{activeTitle}<ChevronDown /></button><span className="challenge-flow-gps"><Zap /> {session?.requiresGpsDistance ? 'GPS CONECTADO' : 'ATIVIDADE EM ANDAMENTO'}</span><article className="challenge-flow-clock"><strong>{time(elapsed)}</strong><small>Tempo decorrido</small></article><div className="challenge-flow-kpis">{activeCardio ? <><article><b>{distance.toFixed(2)}</b><span>Distância (km)</span></article><article><b>{pace}</b><span>Pace médio (min/km)</span></article><article><b>—</b><span>Calorias (kcal)</span></article></> : <><article><b>—</b><span>FC média (bpm)</span></article><article><b>—</b><span>Calorias (kcal)</span></article><article><b>—</b><span>Carga (ton)</span></article><article><b>—</b><span>Intensidade</span></article></>}</div>{!activeCardio && <article className="challenge-flow-zone"><strong>ZONA CARDÍACA</strong><div><i /><i /><i /><i /></div><p>Dados exibidos somente quando houver sensor conectado.</p></article>}<button className="challenge-flow-primary" onClick={onEnd}>{activeCardio ? 'FINALIZAR ATIVIDADE' : 'FINALIZAR TREINO'}</button></section>}
    {complete && <section className="challenge-flow-complete"><div className="challenge-flow-confetti">✦ ✦ ✦ ✦ ✦</div><span className="challenge-flow-check"><Check /></span><p>Parabéns! Você concluiu o desafio e ganhou:</p><strong>+{xp} XP <Zap /></strong><article><b>{activeCardio ? cardio.label.toUpperCase() : 'TREINO DE MUSCULAÇÃO'}</b><small>1/1</small><div /></article><button className="challenge-flow-primary" onClick={onSummary}>{activeCardio ? 'VER RESUMO' : 'VER DESAFIOS DO DIA'}</button><button className="challenge-flow-secondary" onClick={onDone}>VOLTAR PARA DESAFIOS</button></section>}
    {screen === 'cardio-summary' && <section className="challenge-flow-summary"><div className="challenge-flow-summary-title"><div><h2>{cardio.label}</h2><p>Atividade registrada com dados reais.</p></div><span>{time(elapsed)}</span></div>{trajectory && trajectory.length >= 2 ? <ActivityMapView trajectory={trajectory} heightPx={220} /> : <div className="challenge-flow-map is-empty"><MapPin /><span>{cardio.gps ? 'O mapa estará disponível após o GPS registrar o percurso.' : 'Esta modalidade não utiliza GPS.'}</span></div>}<div className="challenge-flow-summary-kpis"><article><b>{time(elapsed)}</b><small>DURAÇÃO</small></article><article><b>{distance.toFixed(2)} km</b><small>DISTÂNCIA</small></article><article><b>{pace}</b><small>PACE MÉDIO</small></article></div><button className="challenge-flow-primary" onClick={onDone}>VOLTAR PARA DESAFIOS</button></section>}
    {screen === 'day-progress' && <section className="challenge-flow-day-progress"><p>Progresso dos desafios concluídos hoje</p><strong>{completedChallengeIds.filter((id) => id === 'workout' || id === 'cardio').length}/2</strong><div className="challenge-flow-day-track"><i style={{ width: `${Math.min(100, completedChallengeIds.filter((id) => id === 'workout' || id === 'cardio').length * 50)}%` }} /></div><article><span className={completedChallengeIds.includes('workout') ? 'is-complete' : ''}><Check /></span><b>TREINO DE MUSCULAÇÃO</b><em>{completedChallengeIds.includes('workout') ? 'CONCLUÍDO' : 'PENDENTE'}</em></article><article><span className={completedChallengeIds.includes('cardio') ? 'is-complete' : ''}><Check /></span><b>CARDIO AERÓBICO</b><em>{completedChallengeIds.includes('cardio') ? 'CONCLUÍDO' : 'PENDENTE'}</em></article><button className="challenge-flow-primary" onClick={onDone}>VOLTAR PARA DESAFIOS</button></section>}
  </main>;
}
