export type ExerciseAssetStatus = 'ready' | 'waiting_for_thumb' | 'waiting_for_demo';

export type OfficialMuscleGroup = 'peito' | 'costas' | 'pernas' | 'ombros' | 'bracos' | 'core';
export type OfficialMuscleSubgroup = 'biceps' | 'triceps';

export interface OfficialExercise {
  id: string;
  name: string;
  muscleGroup: OfficialMuscleGroup;
  muscleSubgroup?: OfficialMuscleSubgroup;
  equipment: string;
  thumbUrl: string;
  /** Optional, verified alternate asset. Never accept a URL generated by the AI. */
  thumbFallbackUrl?: string;
  demoUrl?: string;
  /** Loop only when a real demonstration was authored and reviewed as a loop. */
  demoLoop?: boolean;
  thumbStatus: ExerciseAssetStatus;
  demoStatus: ExerciseAssetStatus;
}

/**
 * Single source for manual plans, local generation, API validation and exercise media.
 * The 27 existing IDs, labels and equipment descriptions are preserved. The historical
 * ID barbell_stiff_deadlift still describes the existing dumbbell exercise.
 * BATCH_01 remains exported for compatibility with existing consumers and saved plans.
 */
export const OFFICIAL_EXERCISES_BATCH_01: OfficialExercise[] = [
  { id: "barbell_bench_press", name: "Supino Reto com Barra", muscleGroup: "peito", equipment: "barra e banco reto", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/barbell_bench_press/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "dumbbell_bench_press", name: "Supino Reto com Halteres", muscleGroup: "peito", equipment: "halteres e banco reto", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/dumbbell_bench_press/thumb.webp", thumbFallbackUrl: "/assets/exercise-library/v1/dumbbell_bench_press/thumb.png", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "incline_dumbbell_press", name: "Supino Inclinado com Halteres", muscleGroup: "peito", equipment: "halteres e banco inclinado", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/incline_dumbbell_press/thumb.webp", thumbFallbackUrl: "/assets/exercise-library/v1/incline_dumbbell_press/thumb.png", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "standing_cable_fly", name: "Crucifixo Reto no Cabo", muscleGroup: "peito", equipment: "cross-over", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/standing_cable_fly/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "pec_deck_fly", name: "Voador / Peck Deck", muscleGroup: "peito", equipment: "máquina peck deck", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/pec_deck_fly/thumb.webp", thumbFallbackUrl: "/assets/exercise-library/v1/pec_deck_fly/thumb.png", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "classic_push_up", name: "Flexão de Braços Clássica", muscleGroup: "peito", equipment: "peso corporal", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/classic_push_up/thumb.webp", thumbFallbackUrl: "/assets/exercise-library/v1/classic_push_up/thumb.png", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "decline_push_up", name: "Flexão de Braços Declinada", muscleGroup: "peito", equipment: "banco e peso corporal", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/decline_push_up/thumb.webp", thumbFallbackUrl: "/assets/exercise-library/v1/decline_push_up/thumb.png", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "incline_push_up", name: "Flexões com Mãos no Banco", muscleGroup: "peito", equipment: "banco e peso corporal", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/incline_push_up/thumb.webp", thumbFallbackUrl: "/assets/exercise-library/v1/incline_push_up/thumb.png", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "barbell_bent_over_row", name: "Remada Curvada com Barra", muscleGroup: "costas", equipment: "barra", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/barbell_bent_over_row/thumb.webp", thumbFallbackUrl: "/assets/exercise-library/v1/barbell_bent_over_row/thumb.png", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "t_bar_row", name: "Remada Cavalinho Neutra", muscleGroup: "costas", equipment: "barra T", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/t_bar_row/thumb.webp", thumbFallbackUrl: "/assets/exercise-library/v1/t_bar_row/thumb.png", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "barbell_back_squat", name: "Agachamento Livre", muscleGroup: "pernas", equipment: "barra e rack", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/barbell_back_squat/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "smith_machine_squat", name: "Agachamento no Smith", muscleGroup: "pernas", equipment: "máquina smith", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/smith_machine_squat/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "leg_press_45", name: "Leg Press 45°", muscleGroup: "pernas", equipment: "máquina leg press", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/leg_press_45/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "hack_squat", name: "Hack Squat", muscleGroup: "pernas", equipment: "máquina hack squat", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/hack_squat/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "leg_extension", name: "Cadeira Extensora", muscleGroup: "pernas", equipment: "máquina extensora", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/leg_extension/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "leg_curl", name: "Mesa Flexora", muscleGroup: "pernas", equipment: "máquina flexora", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/leg_curl/thumb.webp", thumbFallbackUrl: "/assets/exercise-library/v1/leg_curl/thumb.png", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "seated_leg_curl", name: "Cadeira Flexora", muscleGroup: "pernas", equipment: "máquina flexora sentado", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/seated_leg_curl/thumb.webp", thumbFallbackUrl: "/assets/exercise-library/v1/seated_leg_curl/thumb.png", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "barbell_stiff_deadlift", name: "Stiff / Romanian Deadlift", muscleGroup: "pernas", equipment: "halteres", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/barbell_stiff_deadlift/thumb.webp", thumbFallbackUrl: "/assets/exercise-library/v1/barbell_stiff_deadlift/thumb.png", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "dumbbell_lunge", name: "Afundo com Halteres", muscleGroup: "pernas", equipment: "halteres", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/dumbbell_lunge/thumb.webp", thumbFallbackUrl: "/assets/exercise-library/v1/dumbbell_lunge/thumb.png", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "bulgarian_split_squat", name: "Agachamento Búlgaro", muscleGroup: "pernas", equipment: "halteres e banco", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/bulgarian_split_squat/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "dumbbell_walking_lunge", name: "Passada com Halteres", muscleGroup: "pernas", equipment: "halteres", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/dumbbell_walking_lunge/thumb.webp", thumbFallbackUrl: "/assets/exercise-library/v1/dumbbell_walking_lunge/thumb.png", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "hip_adductor_machine", name: "Cadeira Adutora", muscleGroup: "pernas", equipment: "máquina adutora", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/hip_adductor_machine/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "hip_abductor_machine", name: "Cadeira Abdutora", muscleGroup: "pernas", equipment: "máquina abdutora", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/hip_abductor_machine/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "barbell_hip_thrust", name: "Elevação Pélvica / Hip Thrust", muscleGroup: "pernas", equipment: "barra e banco", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/barbell_hip_thrust/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "standing_calf_raise_machine", name: "Panturrilha em Pé", muscleGroup: "pernas", equipment: "máquina de panturrilha", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/standing_calf_raise_machine/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "seated_calf_raise", name: "Panturrilha Sentado", muscleGroup: "pernas", equipment: "máquina de panturrilha sentado", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/seated_calf_raise/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "leg_press_calf_raise", name: "Panturrilha no Leg Press", muscleGroup: "pernas", equipment: "máquina leg press", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/leg_press_calf_raise/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "lat_pulldown", name: "Puxada Frontal na Polia", muscleGroup: "costas", equipment: "polia alta", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/lat_pulldown/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "neutral_grip_lat_pulldown", name: "Puxada Neutra na Polia", muscleGroup: "costas", equipment: "polia alta e puxador neutro", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/neutral_grip_lat_pulldown/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "straight_arm_cable_pulldown", name: "Pulldown com Braços Estendidos", muscleGroup: "costas", equipment: "polia alta", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/straight_arm_cable_pulldown/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "assisted_pull_up", name: "Barra Fixa Assistida no Graviton", muscleGroup: "costas", equipment: "máquina gravitacional", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/assisted_pull_up/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "pull_up", name: "Barra Fixa Pronada", muscleGroup: "costas", equipment: "barra fixa", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/pull_up/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "seated_cable_row", name: "Remada Baixa no Cabo", muscleGroup: "costas", equipment: "polia baixa", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/seated_cable_row/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "single_arm_dumbbell_row", name: "Remada Unilateral com Halter", muscleGroup: "costas", equipment: "halter e banco", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/single_arm_dumbbell_row/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "chest_supported_dumbbell_row", name: "Remada com Halteres e Peito Apoiado", muscleGroup: "costas", equipment: "halteres e banco inclinado", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/chest_supported_dumbbell_row/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "seated_dumbbell_shoulder_press", name: "Desenvolvimento Sentado com Halteres", muscleGroup: "ombros", equipment: "halteres e banco", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/seated_dumbbell_shoulder_press/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "standing_barbell_overhead_press", name: "Desenvolvimento Militar com Barra", muscleGroup: "ombros", equipment: "barra", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/standing_barbell_overhead_press/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "dumbbell_lateral_raise", name: "Elevação Lateral com Halteres", muscleGroup: "ombros", equipment: "halteres", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/dumbbell_lateral_raise/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "single_arm_cable_lateral_raise", name: "Elevação Lateral Unilateral no Cabo", muscleGroup: "ombros", equipment: "polia baixa", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/single_arm_cable_lateral_raise/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "bent_over_dumbbell_reverse_fly", name: "Crucifixo Inverso Curvado com Halteres", muscleGroup: "ombros", equipment: "halteres", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/bent_over_dumbbell_reverse_fly/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "cable_face_pull", name: "Face Pull na Polia", muscleGroup: "ombros", equipment: "polia e corda", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/cable_face_pull/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "reverse_pec_deck_fly", name: "Crucifixo Inverso no Peck Deck", muscleGroup: "ombros", equipment: "máquina peck deck", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/reverse_pec_deck_fly/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "barbell_biceps_curl", name: "Rosca Direta com Barra", muscleGroup: "bracos", muscleSubgroup: "biceps", equipment: "barra", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/barbell_biceps_curl/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "alternating_dumbbell_curl", name: "Rosca Alternada com Halteres", muscleGroup: "bracos", muscleSubgroup: "biceps", equipment: "halteres", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/alternating_dumbbell_curl/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "dumbbell_hammer_curl", name: "Rosca Martelo com Halteres", muscleGroup: "bracos", muscleSubgroup: "biceps", equipment: "halteres", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/dumbbell_hammer_curl/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "cable_biceps_curl", name: "Rosca Direta no Cabo", muscleGroup: "bracos", muscleSubgroup: "biceps", equipment: "polia baixa e barra", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/cable_biceps_curl/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "dumbbell_concentration_curl", name: "Rosca Concentrada com Halter", muscleGroup: "bracos", muscleSubgroup: "biceps", equipment: "halter e banco", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/dumbbell_concentration_curl/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "cable_triceps_pushdown", name: "Tríceps na Polia com Barra", muscleGroup: "bracos", muscleSubgroup: "triceps", equipment: "polia alta e barra", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/cable_triceps_pushdown/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "rope_triceps_pushdown", name: "Tríceps na Polia com Corda", muscleGroup: "bracos", muscleSubgroup: "triceps", equipment: "polia alta e corda", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/rope_triceps_pushdown/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "lying_ez_bar_triceps_extension", name: "Tríceps Testa com Barra EZ", muscleGroup: "bracos", muscleSubgroup: "triceps", equipment: "barra EZ e banco", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/lying_ez_bar_triceps_extension/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "overhead_dumbbell_triceps_extension", name: "Tríceps Francês com Halter", muscleGroup: "bracos", muscleSubgroup: "triceps", equipment: "halter", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/overhead_dumbbell_triceps_extension/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "single_arm_cable_triceps_extension", name: "Tríceps Unilateral na Polia", muscleGroup: "bracos", muscleSubgroup: "triceps", equipment: "polia alta e puxador individual", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/single_arm_cable_triceps_extension/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "abdominal_crunch", name: "Abdominal Crunch", muscleGroup: "core", equipment: "peso corporal", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/abdominal_crunch/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "cable_abdominal_crunch", name: "Abdominal na Polia Alta", muscleGroup: "core", equipment: "polia alta e corda", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/cable_abdominal_crunch/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "reverse_crunch", name: "Abdominal Reverso", muscleGroup: "core", equipment: "peso corporal", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/reverse_crunch/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "lying_leg_raise", name: "Elevação de Pernas Deitado", muscleGroup: "core", equipment: "peso corporal", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/lying_leg_raise/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "dead_bug", name: "Dead Bug", muscleGroup: "core", equipment: "peso corporal", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/dead_bug/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "bird_dog", name: "Bird Dog", muscleGroup: "core", equipment: "peso corporal", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/bird_dog/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
  { id: "standing_cable_pallof_press", name: "Pallof Press em Pé no Cabo", muscleGroup: "core", equipment: "polia e puxador individual", thumbUrl: "/assets/exercise-library/rebuild-2026-09-05/standing_cable_pallof_press/thumb.webp", thumbStatus: "ready", demoStatus: "waiting_for_demo" },
];

export const OFFICIAL_EXERCISE_BY_ID = new Map(OFFICIAL_EXERCISES_BATCH_01.map((exercise) => [exercise.id, exercise]));

export const OFFICIAL_MUSCLE_GROUP_LABELS: Record<OfficialMuscleGroup, string> = {
  peito: 'Peito', costas: 'Costas', pernas: 'Pernas', ombros: 'Ombros', bracos: 'Braços', core: 'Core'
};

/** Categories already collected by the equipment questionnaire; all listed items are required.
 * `maquinas` and `crossover` are broad categories, not a verified inventory of each gym.
 * The display description remains specific about the actual apparatus/attachment.
 */
export const OFFICIAL_EXERCISE_EQUIPMENT_REQUIREMENTS: Record<string, string[]> = {
  barbell_bench_press: ["barra_anilhas", "banco"],
  dumbbell_bench_press: ["halteres", "banco"],
  incline_dumbbell_press: ["halteres", "banco"],
  standing_cable_fly: ["crossover"],
  pec_deck_fly: ["maquinas"],
  classic_push_up: [],
  decline_push_up: ["banco"],
  incline_push_up: ["banco"],
  barbell_bent_over_row: ["barra_anilhas"],
  t_bar_row: ["maquinas"],
  barbell_back_squat: ["barra_anilhas"],
  smith_machine_squat: ["maquinas"],
  leg_press_45: ["maquinas"],
  hack_squat: ["maquinas"],
  leg_extension: ["maquinas"],
  leg_curl: ["maquinas"],
  seated_leg_curl: ["maquinas"],
  barbell_stiff_deadlift: ["halteres"],
  dumbbell_lunge: ["halteres"],
  bulgarian_split_squat: ["halteres", "banco"],
  dumbbell_walking_lunge: ["halteres"],
  hip_adductor_machine: ["maquinas"],
  hip_abductor_machine: ["maquinas"],
  barbell_hip_thrust: ["barra_anilhas", "banco"],
  standing_calf_raise_machine: ["maquinas"],
  seated_calf_raise: ["maquinas"],
  leg_press_calf_raise: ["maquinas"],
  lat_pulldown: ["crossover"],
  neutral_grip_lat_pulldown: ["crossover"],
  straight_arm_cable_pulldown: ["crossover"],
  assisted_pull_up: ["maquinas"],
  pull_up: ["barra_fixa"],
  seated_cable_row: ["crossover"],
  single_arm_dumbbell_row: ["halteres", "banco"],
  chest_supported_dumbbell_row: ["halteres", "banco"],
  seated_dumbbell_shoulder_press: ["halteres", "banco"],
  standing_barbell_overhead_press: ["barra_anilhas"],
  dumbbell_lateral_raise: ["halteres"],
  single_arm_cable_lateral_raise: ["crossover"],
  bent_over_dumbbell_reverse_fly: ["halteres"],
  cable_face_pull: ["crossover"],
  reverse_pec_deck_fly: ["maquinas"],
  barbell_biceps_curl: ["barra_anilhas"],
  alternating_dumbbell_curl: ["halteres"],
  dumbbell_hammer_curl: ["halteres"],
  cable_biceps_curl: ["crossover"],
  dumbbell_concentration_curl: ["halteres", "banco"],
  cable_triceps_pushdown: ["crossover"],
  rope_triceps_pushdown: ["crossover"],
  lying_ez_bar_triceps_extension: ["barra_anilhas", "banco"],
  overhead_dumbbell_triceps_extension: ["halteres"],
  single_arm_cable_triceps_extension: ["crossover"],
  abdominal_crunch: [],
  cable_abdominal_crunch: ["crossover"],
  reverse_crunch: [],
  lying_leg_raise: [],
  dead_bug: [],
  bird_dog: [],
  standing_cable_pallof_press: ["crossover"],
};

/** Unknown IDs or a missing requirement row fail closed instead of becoming bodyweight exercises. */
export function isOfficialExerciseCompatible(exerciseId: string, availableEquipment: readonly string[]): boolean {
  if (!OFFICIAL_EXERCISE_BY_ID.has(exerciseId)) return false;
  const required = OFFICIAL_EXERCISE_EQUIPMENT_REQUIREMENTS[exerciseId];
  return Array.isArray(required) && required.every((item) => availableEquipment.includes(item));
}
